"""
Project:      Voltcraft Data Analyzer
Author:       Valer Bocan, PhD <valer@bocan.ro>
Last updated: June 23rd, 2014

Module
description:  The VoltcraftDataFile module processes data files containing history of voltage, current and power factor,
              as generated by the Voltcraft Energy-Logger 4000.
              
License:      This project is placed in the public domain, hoping that it will be useful to people tinkering with Voltcraft products.
              Derivative works are permitted with or without mentioning the author.
              
Reference:    Voltcraft File Format: http://www2.produktinfo.conrad.com/datenblaetter/125000-149999/125323-da-01-en-Datenprotokoll_SD_card_file_Formatv1_2.pdf
"""

from sys import argv
import VoltcraftInformationFile
import VoltcraftDataFile

if __name__ == "__main__":
    if len(argv) == 1:
        print("Voltcraft Data Analyzer")
        print("Valer Bocan, PhD <valer@bocan.ro>")
        print()
        print("Specify a Voltcraft file as an argument.")
    else:
        for filename in argv[1:]:
            # Attempt to process information file
            info = VoltcraftInformationFile.Process(filename)
            if info:
                print("Voltcraft information file successfully processed.")
                for key in info:
                    print("{0}:{1}".format(key, info[key]))
            else:
                info = VoltcraftDataFile.Process(filename)
                print("Voltcraft data file successfully processed.")
                for key in info:
                    print(key)
